# Quick environment to test different settings in API Gateway

service: sls-apig-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Serverless version
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    description: "Simple APIG listener to return large JSON"
    timeout: 29
    events:
      - http:
          path: test
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false

